### ISSUE TITLE
API authentication method is insecure

### ISSUE THREAD

**Issue by abrie** [abrie/NamibiaOpenDataHackathon#3]
Phonegap apps do not support cookies, and the default Devise authentication scheme is session-based. Therefore the mobile app is unable to maintain an authenticated session. We get around this by verifiying the credentials once, and then attaching the associated email address to subsequent requests. This is not secure.

A possible solution would be something like [RFC 6750: Bearer Tokens]([https://tools.ietf.org/html/rfc6750).

**Comment by pkdon455** [comment]
your whats up

**Comment by abrie** [comment]
Hey @pkdon455. This an issues thread. Issues are a formal way of tracking what needs to be done in order to further develop the app. The issues are [listed here](https://github.com/abrie/NamProNet/issues).

**Comment by pkdon455** [comment]
Good day
can u pls email me more screen shot
